// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFQMBb_QbX-BmM6ZPXC2j6jQhcx6I1svw',
    appId: '1:998918621005:web:f76bde45b0778cd6b0d904',
    messagingSenderId: '998918621005',
    projectId: 'salt-8c0bb',
    authDomain: 'salt-8c0bb.firebaseapp.com',
    storageBucket: 'salt-8c0bb.appspot.com',
    measurementId: 'G-XFWEHJR6PX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCb8r7JZqmA1ne_x4s3jVoQQCVFPKi0Sow',
    appId: '1:998918621005:android:5a08bdada998c810b0d904',
    messagingSenderId: '998918621005',
    projectId: 'salt-8c0bb',
    storageBucket: 'salt-8c0bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUEuh8SM5tcui1924kLmIuhXTICl74t_4',
    appId: '1:998918621005:ios:1682df94c60cd4b0b0d904',
    messagingSenderId: '998918621005',
    projectId: 'salt-8c0bb',
    storageBucket: 'salt-8c0bb.appspot.com',
    androidClientId: '998918621005-1kjo6ooor6a7g76rpjgm61mupumq4tur.apps.googleusercontent.com',
    iosBundleId: 'com.example.clientFunctions',
  );
}
